#! /bin/sh
### BEGIN INIT INFO
# Provides:		  btier
# Required-Start:
# Required-Stop:
# Should-Stop:	   halt reboot kexec
# X-Stop-After:	  umountroot
# Default-Start:
# Default-Stop:	  0 6
# Short-Description: btier creates an automated tiered blockdevice
# Description:
### END INIT INFO

# update-rc.d btier stop 90 0 6 .

PATH=/sbin:/bin:/usr/sbin:/usr/bin
TS=/sbin/btier_setup

. /lib/lsb/init-functions

RETVAL=0

stop() {
	log_action_msg "Unloading the btier devices"
	for tier_dev in /dev/sdtier?; do
		[ ! -b "$tier_dev" ] && continue
		if ! /sbin/btier_setup -d $tier_dev; then
			echo "Failed to deregister tier device : /sbin/btier_setup -d $tier_dev"
			exit 1
		fi
	done
	log_end_msg 0
}

status() {
	# list active sessions
	if [ ! -e /dev/tiercontrol ]; then
		log_action_msg "btier.ko module is not registered"
		exit 1
	fi
	log_action_msg /dev/sdtier*
	exit 0
}

if [ -z "${MODE}" ]; then
	MODE=$1
fi

case "$MODE" in
	start|restart|force-reload)
		log_success_msg "$MODE not provided by init script"
		;;
	status|stop)
		$MODE
		;;
	*)
		log_success_msg "Usage: $0 {stop|status}"
		exit 1
		;;
esac
exit $RETVAL
